server:
  address:     ":8001"
  openapiPath: "/api.json"
  swaggerPath: "/swagger"
  serverRoot: "resource/public/html"

logger:
  level : "all"
  stdout: true

database:
  logger:
    level:   "all"
    stdout:  true
    Path: "resource/log/"

  default:
    link:   "mysql:root:hasd721ba9@tcp(192.168.31.93:39507)/template_starter?charset=utf8mb4&parseTime=true&loc=Local"
    debug:  true
    charset: "utf8mb4" #数据库编码
    dryRun: false #空跑
    maxIdle: 10 #连接池最大闲置的连接数
    maxOpen: 10 #连接池最大打开的连接数
    maxLifetime: "30s" #(单位秒)连接对象可重复使用的时间长度


minio:
  # minio地址
  endpoint: "192.168.31.93:9000"
  accessKey: "minioadmin"
  secretKey: "12345678"
  bucket: "github.com/ciclebyte/bili-pilot"
  useSSL: false
  basePath: "/"