// ================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// You can delete these comments if you wish manually maintain this interface file.
// ================================================================================

package service

import (
	"github.com/gogf/gf/v2/net/ghttp"
)

type IMiddleware interface {
	MiddlewareCORS(r *ghttp.Request)
	RequireAuth(r *ghttp.Request)
	OptionalAuth(r *ghttp.Request)
	RequirePermission(permission string) ghttp.HandlerFunc
	RequireRole(role string) ghttp.HandlerFunc
	RequireTemplateOwnerOrPermission(permission string) ghttp.HandlerFunc
}

var localMiddleware IMiddleware

func Middleware() IMiddleware {
	if localMiddleware == nil {
		panic("implement not found for interface IMiddleware, forgot register?")
	}
	return localMiddleware
}

func RegisterMiddleware(i IMiddleware) {
	localMiddleware = i
}
