// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"github.com/ciclebyte/template_starter/internal/dao/internal"
)

// internalApiKeyLogsDao is internal type for wrapping internal DAO implements.
type internalApiKeyLogsDao = *internal.ApiKeyLogsDao

// apiKeyLogsDao is the data access object for table api_key_logs.
// You can define custom methods on it to extend its functionality as you wish.
type apiKeyLogsDao struct {
	internalApiKeyLogsDao
}

var (
	// ApiKeyLogs is globally public accessible object for table api_key_logs operations.
	ApiKeyLogs = apiKeyLogsDao{
		internal.NewApiKeyLogsDao(),
	}
)

// Fill with you ideas below.
