// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"github.com/ciclebyte/template_starter/internal/dao/internal"
)

// internalApiKeysDao is internal type for wrapping internal DAO implements.
type internalApiKeysDao = *internal.ApiKeysDao

// apiKeysDao is the data access object for table api_keys.
// You can define custom methods on it to extend its functionality as you wish.
type apiKeysDao struct {
	internalApiKeysDao
}

var (
	// ApiKeys is globally public accessible object for table api_keys operations.
	ApiKeys = apiKeysDao{
		internal.NewApiKeysDao(),
	}
)

// Fill with you ideas below.
