// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"github.com/ciclebyte/template_starter/internal/dao/internal"
)

// internalSystemConfigDao is internal type for wrapping internal DAO implements.
type internalSystemConfigDao = *internal.SystemConfigDao

// systemConfigDao is the data access object for table system_config.
// You can define custom methods on it to extend its functionality as you wish.
type systemConfigDao struct {
	internalSystemConfigDao
}

var (
	// SystemConfig is globally public accessible object for table system_config operations.
	SystemConfig = systemConfigDao{
		internal.NewSystemConfigDao(),
	}
)

// Fill with you ideas below.
