// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"github.com/ciclebyte/template_starter/internal/dao/internal"
)

// internalTemplatesDao is internal type for wrapping internal DAO implements.
type internalTemplatesDao = *internal.TemplatesDao

// templatesDao is the data access object for table templates.
// You can define custom methods on it to extend its functionality as you wish.
type templatesDao struct {
	internalTemplatesDao
}

var (
	// Templates is globally public accessible object for table templates operations.
	Templates = templatesDao{
		internal.NewTemplatesDao(),
	}
)

// Fill with you ideas below.
