// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"github.com/ciclebyte/template_starter/internal/dao/internal"
)

// internalTemplateVarPresetsDao is internal type for wrapping internal DAO implements.
type internalTemplateVarPresetsDao = *internal.TemplateVarPresetsDao

// templateVarPresetsDao is the data access object for table template_var_presets.
// You can define custom methods on it to extend its functionality as you wish.
type templateVarPresetsDao struct {
	internalTemplateVarPresetsDao
}

var (
	// TemplateVarPresets is globally public accessible object for table template_var_presets operations.
	TemplateVarPresets = templateVarPresetsDao{
		internal.NewTemplateVarPresetsDao(),
	}
)

// Fill with you ideas below.