// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"github.com/ciclebyte/template_starter/internal/dao/internal"
)

// internalTemplateFilesDao is internal type for wrapping internal DAO implements.
type internalTemplateFilesDao = *internal.TemplateFilesDao

// templateFilesDao is the data access object for table template_files.
// You can define custom methods on it to extend its functionality as you wish.
type templateFilesDao struct {
	internalTemplateFilesDao
}

var (
	// TemplateFiles is globally public accessible object for table template_files operations.
	TemplateFiles = templateFilesDao{
		internal.NewTemplateFilesDao(),
	}
)

// Fill with you ideas below.
