// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"github.com/ciclebyte/template_starter/internal/dao/internal"
)

// internalTemplateTagsDao is internal type for wrapping internal DAO implements.
type internalTemplateTagsDao = *internal.TemplateTagsDao

// templateTagsDao is the data access object for table template_tags.
// You can define custom methods on it to extend its functionality as you wish.
type templateTagsDao struct {
	internalTemplateTagsDao
}

var (
	// TemplateTags is globally public accessible object for table template_tags operations.
	TemplateTags = templateTagsDao{
		internal.NewTemplateTagsDao(),
	}
)

// Fill with you ideas below.