// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"github.com/ciclebyte/template_starter/internal/dao/internal"
)

// internalTemplateLanguagesDao is internal type for wrapping internal DAO implements.
type internalTemplateLanguagesDao = *internal.TemplateLanguagesDao

// templateLanguagesDao is the data access object for table template_languages.
// You can define custom methods on it to extend its functionality as you wish.
type templateLanguagesDao struct {
	internalTemplateLanguagesDao
}

var (
	// TemplateLanguages is globally public accessible object for table template_languages operations.
	TemplateLanguages = templateLanguagesDao{
		internal.NewTemplateLanguagesDao(),
	}
)

// Fill with you ideas below.
