// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"github.com/ciclebyte/template_starter/internal/dao/internal"
)

// internalTemplateExposeFieldsDao is internal type for wrapping internal DAO implements.
type internalTemplateExposeFieldsDao = *internal.TemplateExposeFieldsDao

// templateExposeFieldsDao is the data access object for table template_expose_fields.
// You can define custom methods on it to extend its functionality as you wish.
type templateExposeFieldsDao struct {
	internalTemplateExposeFieldsDao
}

var (
	// TemplateExposeFields is globally public accessible object for table template_expose_fields operations.
	TemplateExposeFields = templateExposeFieldsDao{
		internal.NewTemplateExposeFieldsDao(),
	}
)

// Fill with you ideas below.