// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"github.com/ciclebyte/template_starter/internal/dao/internal"
)

// internalUserSessionsDao is internal type for wrapping internal DAO implements.
type internalUserSessionsDao = *internal.UserSessionsDao

// userSessionsDao is the data access object for table user_sessions.
// You can define custom methods on it to extend its functionality as you wish.
type userSessionsDao struct {
	internalUserSessionsDao
}

var (
	// UserSessions is globally public accessible object for table user_sessions operations.
	UserSessions = userSessionsDao{
		internal.NewUserSessionsDao(),
	}
)

// Fill with you ideas below.
