// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"github.com/ciclebyte/template_starter/internal/dao/internal"
)

// internalVarPresetDao is internal type for wrapping internal DAO implements.
type internalVarPresetDao = *internal.VarPresetDao

// varPresetDao is the data access object for table var_preset.
// You can define custom methods on it to extend its functionality as you wish.
type varPresetDao struct {
	internalVarPresetDao
}

var (
	// VarPreset is globally public accessible object for table var_preset operations.
	VarPreset = varPresetDao{
		internal.NewVarPresetDao(),
	}
)

// Fill with you ideas below.